# License terms and conditions for Janssen Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
apiVersion: v1
appVersion: "1.0.0_a2"
home: https://jans.io
maintainers:
- name: Janssen
email: support@jans.io
description: Helm chart for fido2 service
name: fido2
version: 1.0.0_a2
