# License terms and conditions for Janssen Cloud Native Edition:
# https://www.apache.org/licenses/LICENSE-2.0
# Default values for persistence.
replicaCount: 1

image:
  repository: janssenproject/persistence-loader
  tag: 1.0.0_a1
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
